/*
 * The MIT License
 *
 * Copyright (c) 2025, Nikhil Tiwari
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package hudson.tasks.junit;

import edu.umd.cs.findbugs.annotations.CheckForNull;
import edu.umd.cs.findbugs.annotations.NonNull;
import hudson.ExtensionList;
import hudson.ExtensionPoint;
import hudson.model.Run;
import java.io.IOException;
import jenkins.model.Jenkins;
import org.kohsuke.stapler.StaplerRequest2;
import org.kohsuke.stapler.StaplerResponse2;

/**
 * Extension point that allows plugins to provide custom UI implementations for test results.
 *
 * <p>This enables plugins to completely replace the default JUnit plugin UI with custom
 * visualizations, dashboards, or alternative representations of test data.
 *
 * <p>To register your implementation, put {@link hudson.Extension} on your implementation class.
 *
 * <h2>Security Considerations</h2>
 * <p><strong>WARNING:</strong> Custom UI providers have complete control over the HTTP response
 * when rendering test results. Implementers must take care to prevent security vulnerabilities:
 *
 * <ul>
 * <li><strong>XSS Prevention:</strong> Always escape user-generated content and test data before
 * rendering to HTML. Test names, error messages, and stack traces may contain malicious content.</li>
 * <li><strong>CSRF Protection:</strong> Use Jenkins' CSRF protection mechanisms (crumb tokens) for
 * any forms or state-changing operations.</li>
 * <li><strong>Authentication:</strong> Respect Jenkins' authentication and authorization model.
 * Do not bypass permission checks.</li>
 * <li><strong>Content Security Policy:</strong> Follow Jenkins' Content Security Policy guidelines
 * when including scripts or external resources.</li>
 * <li><strong>Information Disclosure:</strong> Be careful not to expose sensitive information in
 * test results or error messages that should not be visible to all users.</li>
 * </ul>
 *
 * <p>It is the responsibility of the custom UI provider implementation to handle these security
 * concerns properly. The JUnit plugin does not perform additional sanitization or validation
 * of the output generated by custom UI providers.
 *
 * <h2>Usage Example</h2>
 * <pre>
 * {@code
 * @Extension
 * public class MyCustomUIProvider extends CustomUIProvider {
 *     @Override
 *     public String getId() {
 *         return "my-custom-ui";
 *     }
 *
 *     @Override
 *     public String getDisplayName() {
 *         return "My Custom Test UI";
 *     }
 *
 *     @Override
 *     public void renderTestResultUI(TestResult testResult, StaplerRequest2 req, StaplerResponse2 rsp)
 *             throws IOException {
 *         // Render your custom UI
 *         rsp.setContentType("text/html;charset=UTF-8");
 *         // IMPORTANT: Escape user content to prevent XSS
 *         String escapedTitle = Util.escape(testResult.getDisplayName());
 *         rsp.getWriter().println("<html><body><h1>" + escapedTitle + "</h1></body></html>");
 *     }
 * }
 * }
 * </pre>
 *
 * @since TBD
 */
public abstract class CustomUIProvider implements ExtensionPoint {

    /**
     * Returns the unique identifier for this custom UI provider.
     * This will be used to identify and select the provider in configuration.
     *
     * @return the identifier, never null
     */
    @NonNull
    public abstract String getId();

    /**
     * Returns the human-readable display name for this custom UI provider.
     * This will be shown in the Jenkins configuration UI.
     *
     * @return the display name, never null
     */
    @NonNull
    public abstract String getDisplayName();

    /**
     * Renders the custom UI for the entire test result page.
     *
     * <p>This method is called when the user navigates to the test results page
     * and custom UI is enabled. Implementations should write the complete HTML response.
     *
     * <p><strong>Security Note:</strong> This method has full control over the HTTP response.
     * Implementations MUST properly escape all user-generated content including test names,
     * error messages, and stack traces to prevent XSS attacks. Use {@link hudson.Util#escape(String)}
     * or equivalent methods to sanitize output.
     *
     * @param testResult the test result data to render
     * @param req the Stapler request
     * @param rsp the Stapler response
     * @throws IOException if an I/O error occurs while rendering
     */
    public abstract void renderTestResultUI(
            @NonNull TestResult testResult, @NonNull StaplerRequest2 req, @NonNull StaplerResponse2 rsp)
            throws IOException;

    /**
     * Renders the custom UI for an individual test case.
     *
     * <p>This method is called when the user navigates to a specific test case page
     * and custom UI is enabled. The default implementation redirects to the main test result UI.
     *
     * <p><strong>Security Note:</strong> This method has full control over the HTTP response.
     * Implementations MUST properly escape all user-generated content including test names,
     * error messages, and stack traces to prevent XSS attacks. Use {@link hudson.Util#escape(String)}
     * or equivalent methods to sanitize output.
     *
     * @param caseResult the test case result to render
     * @param req the Stapler request
     * @param rsp the Stapler response
     * @throws IOException if an I/O error occurs while rendering
     */
    public void renderCaseResultUI(
            @NonNull CaseResult caseResult, @NonNull StaplerRequest2 req, @NonNull StaplerResponse2 rsp)
            throws IOException {
        // Default implementation - redirect to parent test result
        rsp.sendRedirect2("../..");
    }

    /**
     * Determines whether this custom UI provider can handle the given run.
     *
     * <p>This method allows providers to opt-in or opt-out based on the build type,
     * project configuration, or other criteria.
     *
     * @param run the run to check
     * @return true if this provider can handle the run, false otherwise
     */
    public boolean isApplicable(@NonNull Run<?, ?> run) {
        return true;
    }

    /**
     * Returns all registered custom UI providers.
     *
     * @return list of all custom UI providers
     */
    @NonNull
    public static ExtensionList<CustomUIProvider> all() {
        return Jenkins.get().getExtensionList(CustomUIProvider.class);
    }

    /**
     * Finds a custom UI provider by its identifier.
     *
     * @param id the provider identifier
     * @return the provider instance if found, null otherwise
     */
    @CheckForNull
    public static CustomUIProvider findById(@CheckForNull String id) {
        if (id == null || id.isEmpty()) {
            return null;
        }
        for (CustomUIProvider provider : all()) {
            String providerId = provider.getId();
            if (providerId != null && providerId.equals(id)) {
                return provider;
            }
        }
        return null;
    }
}
